# Generated by Django 2.2.5 on 2019-11-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contenuto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titolo',
        ),
    ]
