# Generated by Django 2.2.5 on 2019-11-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_approved'),
        ('comments', '0002_auto_20191120_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='experiences.Experience'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.Post'),
        ),
    ]
