# Generated by Django 2.2.5 on 2019-11-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
