# Generated by Django 2.2.5 on 2019-11-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='content',
            new_name='contenuto',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='title',
            new_name='titolo',
        ),
    ]
